In [1]:
import torch
import numpy as np
from Activation import ReLU, Tanh
from Layer import Linear
from Sequential import Sequential
from Loss import LossMSE

In [2]:
def test_accuracy(model, test_input, test_target):
    
    output = model.forward(test_input)
    
    output[output >= 0] = 1
    output[output < 0] = -1
    goodValue = torch.full((len(output), 1), 0)
    goodValue[output == test_target] = 1
    return goodValue.sum()/len(goodValue)

In [3]:
loss = LossMSE()
model = Sequential(
            Linear(2, 25),
            ReLU(),
            Linear(25, 50),
            ReLU(),
            Linear(50, 25),
            ReLU(),
            Linear(25, 1)
        )

In [4]:
train_input = torch.rand((1000,2))
train_target = torch.rand((1000,1))
train_target[((train_input-0.5)**2).sum(1) < 1/(2*np.pi)] = -1 
train_target[((train_input-0.5)**2).sum(1) >= 1/(2*np.pi)] = 1

test_input = torch.rand((1000,2))
test_target = torch.rand((1000,1))
test_target[((test_input-0.5)**2).sum(1) < 1/(2*np.pi)] = -1 
test_target[((test_input-0.5)**2).sum(1) >= 1/(2*np.pi)] = 1

In [5]:
epochs = 40000
for i in range(epochs):


    output = model.forward(train_input)

    gradwrrtxL = loss.backward(output, train_target)
    model.backward(gradwrrtxL)

    if i % 10 == 0:
        test_accuracyV = test_accuracy(model, test_input, test_target)
        
        print(loss.forward(output, train_target), test_accuracyV, test_accuracy(model, train_input, train_target))


tensor(2842.6160) tensor(0.5180) tensor(0.4900)
tensor(6.7791) tensor(0.6220) tensor(0.6290)
tensor(6.2327) tensor(0.6370) tensor(0.6510)
tensor(5.8027) tensor(0.6500) tensor(0.6630)
tensor(5.4541) tensor(0.6610) tensor(0.6710)
tensor(5.1670) tensor(0.6680) tensor(0.6770)
tensor(4.9299) tensor(0.6750) tensor(0.6880)
tensor(4.7242) tensor(0.6820) tensor(0.6900)
tensor(4.5329) tensor(0.6870) tensor(0.6930)
tensor(4.3551) tensor(0.6860) tensor(0.6990)
tensor(4.1954) tensor(0.6890) tensor(0.7030)
tensor(4.0486) tensor(0.6950) tensor(0.7050)
tensor(3.9152) tensor(0.6960) tensor(0.7090)
tensor(3.7928) tensor(0.6970) tensor(0.7130)
tensor(3.6776) tensor(0.6980) tensor(0.7170)
tensor(3.5686) tensor(0.6990) tensor(0.7190)
tensor(3.4667) tensor(0.6990) tensor(0.7200)
tensor(3.3724) tensor(0.6980) tensor(0.7200)
tensor(3.2824) tensor(0.6970) tensor(0.7170)
tensor(3.1979) tensor(0.6970) tensor(0.7170)
tensor(3.1183) tensor(0.6980) tensor(0.7170)
tensor(3.0433) tensor(0.7000) tensor(0.7180)
tensor(

tensor(1.5799) tensor(0.6360) tensor(0.6460)
tensor(1.5776) tensor(0.6370) tensor(0.6460)
tensor(1.5752) tensor(0.6370) tensor(0.6460)
tensor(1.5729) tensor(0.6380) tensor(0.6460)
tensor(1.5705) tensor(0.6380) tensor(0.6460)
tensor(1.5682) tensor(0.6380) tensor(0.6460)
tensor(1.5659) tensor(0.6390) tensor(0.6460)
tensor(1.5636) tensor(0.6390) tensor(0.6460)
tensor(1.5613) tensor(0.6380) tensor(0.6450)
tensor(1.5591) tensor(0.6380) tensor(0.6450)
tensor(1.5568) tensor(0.6380) tensor(0.6450)
tensor(1.5545) tensor(0.6380) tensor(0.6460)
tensor(1.5522) tensor(0.6380) tensor(0.6450)
tensor(1.5499) tensor(0.6370) tensor(0.6450)
tensor(1.5477) tensor(0.6380) tensor(0.6450)
tensor(1.5454) tensor(0.6370) tensor(0.6450)
tensor(1.5432) tensor(0.6370) tensor(0.6450)
tensor(1.5410) tensor(0.6370) tensor(0.6450)
tensor(1.5389) tensor(0.6370) tensor(0.6450)
tensor(1.5367) tensor(0.6370) tensor(0.6450)
tensor(1.5345) tensor(0.6370) tensor(0.6460)
tensor(1.5324) tensor(0.6380) tensor(0.6460)
tensor(1.5

tensor(1.2321) tensor(0.6300) tensor(0.6400)
tensor(1.2308) tensor(0.6300) tensor(0.6400)
tensor(1.2294) tensor(0.6310) tensor(0.6400)
tensor(1.2281) tensor(0.6310) tensor(0.6400)
tensor(1.2267) tensor(0.6290) tensor(0.6410)
tensor(1.2254) tensor(0.6290) tensor(0.6410)
tensor(1.2241) tensor(0.6290) tensor(0.6410)
tensor(1.2227) tensor(0.6290) tensor(0.6410)
tensor(1.2214) tensor(0.6290) tensor(0.6400)
tensor(1.2200) tensor(0.6290) tensor(0.6390)
tensor(1.2187) tensor(0.6300) tensor(0.6390)
tensor(1.2173) tensor(0.6300) tensor(0.6400)
tensor(1.2159) tensor(0.6290) tensor(0.6410)
tensor(1.2144) tensor(0.6300) tensor(0.6410)
tensor(1.2130) tensor(0.6300) tensor(0.6420)
tensor(1.2117) tensor(0.6320) tensor(0.6420)
tensor(1.2103) tensor(0.6330) tensor(0.6410)
tensor(1.2089) tensor(0.6330) tensor(0.6410)
tensor(1.2075) tensor(0.6320) tensor(0.6410)
tensor(1.2060) tensor(0.6310) tensor(0.6410)
tensor(1.2045) tensor(0.6310) tensor(0.6410)
tensor(1.2030) tensor(0.6310) tensor(0.6410)
tensor(1.2

tensor(1.0346) tensor(0.6310) tensor(0.6390)
tensor(1.0339) tensor(0.6320) tensor(0.6390)
tensor(1.0332) tensor(0.6320) tensor(0.6390)
tensor(1.0325) tensor(0.6320) tensor(0.6390)
tensor(1.0318) tensor(0.6320) tensor(0.6390)
tensor(1.0311) tensor(0.6320) tensor(0.6390)
tensor(1.0305) tensor(0.6330) tensor(0.6390)
tensor(1.0298) tensor(0.6330) tensor(0.6390)
tensor(1.0291) tensor(0.6330) tensor(0.6390)
tensor(1.0284) tensor(0.6330) tensor(0.6390)
tensor(1.0278) tensor(0.6330) tensor(0.6390)
tensor(1.0271) tensor(0.6320) tensor(0.6400)
tensor(1.0264) tensor(0.6320) tensor(0.6390)
tensor(1.0258) tensor(0.6310) tensor(0.6390)
tensor(1.0251) tensor(0.6310) tensor(0.6380)
tensor(1.0245) tensor(0.6310) tensor(0.6390)
tensor(1.0238) tensor(0.6310) tensor(0.6400)
tensor(1.0232) tensor(0.6330) tensor(0.6400)
tensor(1.0225) tensor(0.6330) tensor(0.6410)
tensor(1.0218) tensor(0.6330) tensor(0.6410)
tensor(1.0212) tensor(0.6330) tensor(0.6410)
tensor(1.0205) tensor(0.6330) tensor(0.6410)
tensor(1.0

tensor(0.9560) tensor(0.6710) tensor(0.6770)
tensor(0.9558) tensor(0.6720) tensor(0.6760)
tensor(0.9556) tensor(0.6720) tensor(0.6760)
tensor(0.9554) tensor(0.6730) tensor(0.6780)
tensor(0.9552) tensor(0.6730) tensor(0.6800)
tensor(0.9550) tensor(0.6720) tensor(0.6800)
tensor(0.9548) tensor(0.6720) tensor(0.6810)
tensor(0.9546) tensor(0.6720) tensor(0.6810)
tensor(0.9544) tensor(0.6720) tensor(0.6820)
tensor(0.9542) tensor(0.6720) tensor(0.6820)
tensor(0.9540) tensor(0.6720) tensor(0.6820)
tensor(0.9538) tensor(0.6720) tensor(0.6840)
tensor(0.9536) tensor(0.6720) tensor(0.6840)
tensor(0.9534) tensor(0.6710) tensor(0.6840)
tensor(0.9532) tensor(0.6710) tensor(0.6840)
tensor(0.9531) tensor(0.6710) tensor(0.6830)
tensor(0.9529) tensor(0.6700) tensor(0.6830)
tensor(0.9527) tensor(0.6700) tensor(0.6820)
tensor(0.9525) tensor(0.6700) tensor(0.6810)
tensor(0.9523) tensor(0.6700) tensor(0.6810)
tensor(0.9522) tensor(0.6710) tensor(0.6820)
tensor(0.9520) tensor(0.6710) tensor(0.6820)
tensor(0.9

tensor(0.9275) tensor(0.6690) tensor(0.6850)
tensor(0.9273) tensor(0.6690) tensor(0.6850)
tensor(0.9272) tensor(0.6700) tensor(0.6860)
tensor(0.9270) tensor(0.6700) tensor(0.6860)
tensor(0.9268) tensor(0.6700) tensor(0.6870)
tensor(0.9266) tensor(0.6700) tensor(0.6870)
tensor(0.9264) tensor(0.6690) tensor(0.6870)
tensor(0.9261) tensor(0.6690) tensor(0.6870)
tensor(0.9259) tensor(0.6690) tensor(0.6870)
tensor(0.9257) tensor(0.6690) tensor(0.6880)
tensor(0.9255) tensor(0.6690) tensor(0.6880)
tensor(0.9253) tensor(0.6690) tensor(0.6890)
tensor(0.9251) tensor(0.6690) tensor(0.6890)
tensor(0.9249) tensor(0.6690) tensor(0.6890)
tensor(0.9247) tensor(0.6690) tensor(0.6900)
tensor(0.9245) tensor(0.6690) tensor(0.6900)
tensor(0.9243) tensor(0.6690) tensor(0.6900)
tensor(0.9241) tensor(0.6690) tensor(0.6900)
tensor(0.9238) tensor(0.6690) tensor(0.6900)
tensor(0.9236) tensor(0.6690) tensor(0.6910)
tensor(0.9234) tensor(0.6690) tensor(0.6920)
tensor(0.9232) tensor(0.6690) tensor(0.6930)
tensor(0.9

tensor(0.8729) tensor(0.7100) tensor(0.7250)
tensor(0.8726) tensor(0.7110) tensor(0.7250)
tensor(0.8722) tensor(0.7120) tensor(0.7250)
tensor(0.8719) tensor(0.7120) tensor(0.7250)
tensor(0.8715) tensor(0.7140) tensor(0.7250)
tensor(0.8711) tensor(0.7140) tensor(0.7250)
tensor(0.8708) tensor(0.7150) tensor(0.7260)
tensor(0.8704) tensor(0.7150) tensor(0.7260)
tensor(0.8700) tensor(0.7150) tensor(0.7260)
tensor(0.8697) tensor(0.7150) tensor(0.7260)
tensor(0.8693) tensor(0.7150) tensor(0.7260)
tensor(0.8689) tensor(0.7160) tensor(0.7260)
tensor(0.8685) tensor(0.7170) tensor(0.7260)
tensor(0.8682) tensor(0.7170) tensor(0.7260)
tensor(0.8678) tensor(0.7170) tensor(0.7260)
tensor(0.8674) tensor(0.7170) tensor(0.7260)
tensor(0.8670) tensor(0.7170) tensor(0.7270)
tensor(0.8666) tensor(0.7170) tensor(0.7280)
tensor(0.8663) tensor(0.7170) tensor(0.7280)
tensor(0.8659) tensor(0.7180) tensor(0.7280)
tensor(0.8655) tensor(0.7180) tensor(0.7290)
tensor(0.8651) tensor(0.7180) tensor(0.7300)
tensor(0.8

tensor(0.8026) tensor(0.7430) tensor(0.7670)
tensor(0.8022) tensor(0.7430) tensor(0.7670)
tensor(0.8019) tensor(0.7430) tensor(0.7680)
tensor(0.8015) tensor(0.7420) tensor(0.7680)
tensor(0.8011) tensor(0.7420) tensor(0.7690)
tensor(0.8007) tensor(0.7420) tensor(0.7690)
tensor(0.8004) tensor(0.7430) tensor(0.7690)
tensor(0.8000) tensor(0.7440) tensor(0.7690)
tensor(0.7996) tensor(0.7450) tensor(0.7690)
tensor(0.7992) tensor(0.7440) tensor(0.7690)
tensor(0.7989) tensor(0.7440) tensor(0.7710)
tensor(0.7985) tensor(0.7440) tensor(0.7710)
tensor(0.7981) tensor(0.7440) tensor(0.7710)
tensor(0.7977) tensor(0.7440) tensor(0.7710)
tensor(0.7973) tensor(0.7450) tensor(0.7710)
tensor(0.7970) tensor(0.7450) tensor(0.7710)
tensor(0.7966) tensor(0.7450) tensor(0.7710)
tensor(0.7962) tensor(0.7450) tensor(0.7710)
tensor(0.7958) tensor(0.7460) tensor(0.7710)
tensor(0.7955) tensor(0.7460) tensor(0.7710)
tensor(0.7951) tensor(0.7460) tensor(0.7710)
tensor(0.7947) tensor(0.7460) tensor(0.7710)
tensor(0.7

tensor(0.7374) tensor(0.7720) tensor(0.7900)
tensor(0.7371) tensor(0.7720) tensor(0.7900)
tensor(0.7367) tensor(0.7720) tensor(0.7900)
tensor(0.7364) tensor(0.7720) tensor(0.7900)
tensor(0.7361) tensor(0.7720) tensor(0.7900)
tensor(0.7358) tensor(0.7730) tensor(0.7900)
tensor(0.7355) tensor(0.7730) tensor(0.7900)
tensor(0.7351) tensor(0.7730) tensor(0.7900)
tensor(0.7348) tensor(0.7730) tensor(0.7900)
tensor(0.7345) tensor(0.7730) tensor(0.7900)
tensor(0.7342) tensor(0.7730) tensor(0.7900)
tensor(0.7339) tensor(0.7730) tensor(0.7900)
tensor(0.7336) tensor(0.7730) tensor(0.7900)
tensor(0.7332) tensor(0.7730) tensor(0.7900)
tensor(0.7329) tensor(0.7730) tensor(0.7900)
tensor(0.7326) tensor(0.7730) tensor(0.7900)
tensor(0.7323) tensor(0.7730) tensor(0.7900)
tensor(0.7320) tensor(0.7730) tensor(0.7900)
tensor(0.7317) tensor(0.7730) tensor(0.7900)
tensor(0.7314) tensor(0.7730) tensor(0.7900)
tensor(0.7310) tensor(0.7720) tensor(0.7900)
tensor(0.7307) tensor(0.7730) tensor(0.7900)
tensor(0.7

tensor(0.6799) tensor(0.7940) tensor(0.8130)
tensor(0.6796) tensor(0.7960) tensor(0.8130)
tensor(0.6793) tensor(0.7960) tensor(0.8130)
tensor(0.6790) tensor(0.7960) tensor(0.8130)
tensor(0.6787) tensor(0.7960) tensor(0.8130)
tensor(0.6784) tensor(0.7960) tensor(0.8130)
tensor(0.6781) tensor(0.7980) tensor(0.8140)
tensor(0.6778) tensor(0.7980) tensor(0.8140)
tensor(0.6774) tensor(0.7990) tensor(0.8140)
tensor(0.6771) tensor(0.7990) tensor(0.8150)
tensor(0.6768) tensor(0.7990) tensor(0.8150)
tensor(0.6765) tensor(0.7990) tensor(0.8150)
tensor(0.6762) tensor(0.7980) tensor(0.8160)
tensor(0.6759) tensor(0.7980) tensor(0.8170)
tensor(0.6756) tensor(0.7990) tensor(0.8170)
tensor(0.6753) tensor(0.7990) tensor(0.8170)
tensor(0.6750) tensor(0.7990) tensor(0.8170)
tensor(0.6747) tensor(0.7990) tensor(0.8170)
tensor(0.6743) tensor(0.7990) tensor(0.8170)
tensor(0.6740) tensor(0.8000) tensor(0.8170)
tensor(0.6737) tensor(0.8000) tensor(0.8170)
tensor(0.6734) tensor(0.8000) tensor(0.8170)
tensor(0.6

tensor(0.6266) tensor(0.8330) tensor(0.8340)
tensor(0.6264) tensor(0.8330) tensor(0.8340)
tensor(0.6261) tensor(0.8330) tensor(0.8340)
tensor(0.6259) tensor(0.8330) tensor(0.8350)
tensor(0.6256) tensor(0.8340) tensor(0.8350)
tensor(0.6254) tensor(0.8340) tensor(0.8350)
tensor(0.6251) tensor(0.8350) tensor(0.8350)
tensor(0.6249) tensor(0.8350) tensor(0.8350)
tensor(0.6246) tensor(0.8350) tensor(0.8350)
tensor(0.6244) tensor(0.8350) tensor(0.8350)
tensor(0.6241) tensor(0.8360) tensor(0.8350)
tensor(0.6239) tensor(0.8360) tensor(0.8350)
tensor(0.6236) tensor(0.8360) tensor(0.8350)
tensor(0.6234) tensor(0.8360) tensor(0.8350)
tensor(0.6231) tensor(0.8360) tensor(0.8350)
tensor(0.6229) tensor(0.8360) tensor(0.8350)
tensor(0.6226) tensor(0.8360) tensor(0.8360)
tensor(0.6224) tensor(0.8360) tensor(0.8360)
tensor(0.6221) tensor(0.8360) tensor(0.8360)
tensor(0.6219) tensor(0.8360) tensor(0.8360)
tensor(0.6217) tensor(0.8360) tensor(0.8360)
tensor(0.6214) tensor(0.8360) tensor(0.8360)
tensor(0.6

tensor(0.5853) tensor(0.8520) tensor(0.8460)
tensor(0.5851) tensor(0.8520) tensor(0.8460)
tensor(0.5849) tensor(0.8520) tensor(0.8460)
tensor(0.5847) tensor(0.8520) tensor(0.8460)
tensor(0.5845) tensor(0.8520) tensor(0.8460)
tensor(0.5843) tensor(0.8520) tensor(0.8460)
tensor(0.5841) tensor(0.8520) tensor(0.8460)
tensor(0.5839) tensor(0.8520) tensor(0.8460)
tensor(0.5837) tensor(0.8520) tensor(0.8460)
tensor(0.5835) tensor(0.8520) tensor(0.8460)
tensor(0.5833) tensor(0.8520) tensor(0.8460)
tensor(0.5831) tensor(0.8520) tensor(0.8460)
tensor(0.5829) tensor(0.8520) tensor(0.8460)
tensor(0.5827) tensor(0.8510) tensor(0.8460)
tensor(0.5825) tensor(0.8510) tensor(0.8460)
tensor(0.5823) tensor(0.8510) tensor(0.8460)
tensor(0.5821) tensor(0.8510) tensor(0.8460)
tensor(0.5819) tensor(0.8510) tensor(0.8460)
tensor(0.5817) tensor(0.8510) tensor(0.8460)
tensor(0.5816) tensor(0.8510) tensor(0.8460)
tensor(0.5814) tensor(0.8510) tensor(0.8460)
tensor(0.5812) tensor(0.8510) tensor(0.8460)
tensor(0.5

tensor(0.5513) tensor(0.8560) tensor(0.8570)
tensor(0.5511) tensor(0.8560) tensor(0.8570)
tensor(0.5510) tensor(0.8560) tensor(0.8570)
tensor(0.5508) tensor(0.8550) tensor(0.8570)
tensor(0.5506) tensor(0.8550) tensor(0.8570)
tensor(0.5504) tensor(0.8560) tensor(0.8570)
tensor(0.5503) tensor(0.8560) tensor(0.8570)
tensor(0.5501) tensor(0.8560) tensor(0.8570)
tensor(0.5499) tensor(0.8560) tensor(0.8570)
tensor(0.5498) tensor(0.8570) tensor(0.8580)
tensor(0.5496) tensor(0.8570) tensor(0.8580)
tensor(0.5494) tensor(0.8570) tensor(0.8590)
tensor(0.5492) tensor(0.8570) tensor(0.8590)
tensor(0.5491) tensor(0.8570) tensor(0.8590)
tensor(0.5489) tensor(0.8570) tensor(0.8590)
tensor(0.5487) tensor(0.8580) tensor(0.8590)
tensor(0.5486) tensor(0.8580) tensor(0.8590)
tensor(0.5484) tensor(0.8580) tensor(0.8600)
tensor(0.5482) tensor(0.8580) tensor(0.8600)
tensor(0.5480) tensor(0.8580) tensor(0.8600)
tensor(0.5479) tensor(0.8580) tensor(0.8600)
tensor(0.5477) tensor(0.8580) tensor(0.8600)
tensor(0.5

tensor(0.5228) tensor(0.8600) tensor(0.8650)
tensor(0.5227) tensor(0.8600) tensor(0.8650)
tensor(0.5226) tensor(0.8600) tensor(0.8650)
tensor(0.5224) tensor(0.8600) tensor(0.8650)
tensor(0.5223) tensor(0.8600) tensor(0.8650)
tensor(0.5222) tensor(0.8600) tensor(0.8650)
tensor(0.5220) tensor(0.8600) tensor(0.8660)
tensor(0.5219) tensor(0.8600) tensor(0.8660)
tensor(0.5218) tensor(0.8600) tensor(0.8660)
tensor(0.5217) tensor(0.8600) tensor(0.8660)
tensor(0.5215) tensor(0.8600) tensor(0.8660)
tensor(0.5214) tensor(0.8610) tensor(0.8660)
tensor(0.5213) tensor(0.8610) tensor(0.8660)
tensor(0.5212) tensor(0.8610) tensor(0.8660)
tensor(0.5210) tensor(0.8610) tensor(0.8660)
tensor(0.5209) tensor(0.8610) tensor(0.8660)
tensor(0.5208) tensor(0.8610) tensor(0.8660)
tensor(0.5207) tensor(0.8600) tensor(0.8670)
tensor(0.5205) tensor(0.8600) tensor(0.8670)
tensor(0.5204) tensor(0.8600) tensor(0.8670)
tensor(0.5203) tensor(0.8600) tensor(0.8670)
tensor(0.5202) tensor(0.8600) tensor(0.8670)
tensor(0.5

tensor(0.5037) tensor(0.8640) tensor(0.8640)
tensor(0.5036) tensor(0.8640) tensor(0.8640)
tensor(0.5035) tensor(0.8640) tensor(0.8640)
tensor(0.5035) tensor(0.8640) tensor(0.8660)
tensor(0.5034) tensor(0.8640) tensor(0.8660)
tensor(0.5033) tensor(0.8640) tensor(0.8660)
tensor(0.5032) tensor(0.8640) tensor(0.8660)
tensor(0.5031) tensor(0.8640) tensor(0.8660)
tensor(0.5030) tensor(0.8640) tensor(0.8660)
tensor(0.5030) tensor(0.8640) tensor(0.8660)
tensor(0.5029) tensor(0.8650) tensor(0.8660)
tensor(0.5028) tensor(0.8650) tensor(0.8660)
tensor(0.5027) tensor(0.8650) tensor(0.8660)
tensor(0.5026) tensor(0.8660) tensor(0.8660)
tensor(0.5025) tensor(0.8660) tensor(0.8660)
tensor(0.5025) tensor(0.8660) tensor(0.8660)
tensor(0.5024) tensor(0.8660) tensor(0.8660)
tensor(0.5023) tensor(0.8660) tensor(0.8670)
tensor(0.5022) tensor(0.8660) tensor(0.8670)
tensor(0.5021) tensor(0.8660) tensor(0.8670)
tensor(0.5020) tensor(0.8660) tensor(0.8670)
tensor(0.5020) tensor(0.8660) tensor(0.8670)
tensor(0.5

tensor(0.4906) tensor(0.8810) tensor(0.8720)
tensor(0.4905) tensor(0.8810) tensor(0.8720)
tensor(0.4904) tensor(0.8810) tensor(0.8720)
tensor(0.4904) tensor(0.8810) tensor(0.8720)
tensor(0.4903) tensor(0.8810) tensor(0.8720)
tensor(0.4903) tensor(0.8810) tensor(0.8720)
tensor(0.4902) tensor(0.8810) tensor(0.8720)
tensor(0.4902) tensor(0.8810) tensor(0.8720)
tensor(0.4901) tensor(0.8810) tensor(0.8720)
tensor(0.4901) tensor(0.8810) tensor(0.8720)
tensor(0.4900) tensor(0.8810) tensor(0.8720)
tensor(0.4900) tensor(0.8810) tensor(0.8720)
tensor(0.4899) tensor(0.8810) tensor(0.8720)
tensor(0.4899) tensor(0.8810) tensor(0.8720)
tensor(0.4898) tensor(0.8810) tensor(0.8720)
tensor(0.4897) tensor(0.8810) tensor(0.8720)
tensor(0.4897) tensor(0.8810) tensor(0.8720)
tensor(0.4896) tensor(0.8810) tensor(0.8720)
tensor(0.4896) tensor(0.8810) tensor(0.8720)
tensor(0.4895) tensor(0.8810) tensor(0.8720)
tensor(0.4895) tensor(0.8810) tensor(0.8730)
tensor(0.4894) tensor(0.8810) tensor(0.8730)
tensor(0.4

tensor(0.4815) tensor(0.8860) tensor(0.8790)
tensor(0.4815) tensor(0.8860) tensor(0.8790)
tensor(0.4815) tensor(0.8860) tensor(0.8790)
tensor(0.4814) tensor(0.8860) tensor(0.8790)
tensor(0.4814) tensor(0.8860) tensor(0.8790)
tensor(0.4813) tensor(0.8850) tensor(0.8800)
tensor(0.4813) tensor(0.8850) tensor(0.8800)
tensor(0.4812) tensor(0.8850) tensor(0.8800)
tensor(0.4812) tensor(0.8850) tensor(0.8800)
tensor(0.4811) tensor(0.8850) tensor(0.8800)
tensor(0.4811) tensor(0.8860) tensor(0.8800)
tensor(0.4810) tensor(0.8860) tensor(0.8800)
tensor(0.4810) tensor(0.8860) tensor(0.8810)
tensor(0.4809) tensor(0.8860) tensor(0.8810)
tensor(0.4809) tensor(0.8860) tensor(0.8810)
tensor(0.4809) tensor(0.8860) tensor(0.8810)
tensor(0.4808) tensor(0.8860) tensor(0.8810)
tensor(0.4808) tensor(0.8860) tensor(0.8810)
tensor(0.4807) tensor(0.8860) tensor(0.8810)
tensor(0.4807) tensor(0.8860) tensor(0.8810)
tensor(0.4806) tensor(0.8860) tensor(0.8810)
tensor(0.4806) tensor(0.8860) tensor(0.8810)
tensor(0.4

tensor(0.4737) tensor(0.8890) tensor(0.8800)
tensor(0.4736) tensor(0.8890) tensor(0.8800)
tensor(0.4736) tensor(0.8890) tensor(0.8800)
tensor(0.4735) tensor(0.8890) tensor(0.8800)
tensor(0.4735) tensor(0.8890) tensor(0.8800)
tensor(0.4734) tensor(0.8890) tensor(0.8800)
tensor(0.4734) tensor(0.8890) tensor(0.8800)
tensor(0.4734) tensor(0.8900) tensor(0.8800)
tensor(0.4733) tensor(0.8900) tensor(0.8810)
tensor(0.4733) tensor(0.8900) tensor(0.8810)
tensor(0.4732) tensor(0.8910) tensor(0.8810)
tensor(0.4732) tensor(0.8910) tensor(0.8810)
tensor(0.4732) tensor(0.8910) tensor(0.8810)
tensor(0.4731) tensor(0.8910) tensor(0.8810)
tensor(0.4731) tensor(0.8900) tensor(0.8810)
tensor(0.4730) tensor(0.8900) tensor(0.8800)
tensor(0.4730) tensor(0.8900) tensor(0.8800)
tensor(0.4730) tensor(0.8900) tensor(0.8800)
tensor(0.4729) tensor(0.8900) tensor(0.8800)
tensor(0.4729) tensor(0.8900) tensor(0.8800)
tensor(0.4728) tensor(0.8900) tensor(0.8800)
tensor(0.4728) tensor(0.8900) tensor(0.8800)
tensor(0.4

tensor(0.4666) tensor(0.8990) tensor(0.8840)
tensor(0.4666) tensor(0.8990) tensor(0.8840)
tensor(0.4665) tensor(0.8990) tensor(0.8840)
tensor(0.4665) tensor(0.8990) tensor(0.8840)
tensor(0.4665) tensor(0.8990) tensor(0.8840)
tensor(0.4664) tensor(0.9000) tensor(0.8840)
tensor(0.4664) tensor(0.9000) tensor(0.8840)
tensor(0.4663) tensor(0.9000) tensor(0.8840)
tensor(0.4663) tensor(0.9000) tensor(0.8840)
tensor(0.4663) tensor(0.9000) tensor(0.8840)
tensor(0.4662) tensor(0.9000) tensor(0.8840)
tensor(0.4662) tensor(0.9000) tensor(0.8840)
tensor(0.4662) tensor(0.9000) tensor(0.8840)
tensor(0.4661) tensor(0.9000) tensor(0.8840)
tensor(0.4661) tensor(0.9000) tensor(0.8840)
tensor(0.4660) tensor(0.9000) tensor(0.8840)
tensor(0.4660) tensor(0.9000) tensor(0.8840)
tensor(0.4660) tensor(0.9000) tensor(0.8840)
tensor(0.4659) tensor(0.9000) tensor(0.8840)
tensor(0.4659) tensor(0.9000) tensor(0.8840)
tensor(0.4659) tensor(0.9000) tensor(0.8840)
tensor(0.4658) tensor(0.9000) tensor(0.8840)
tensor(0.4

tensor(0.4596) tensor(0.9020) tensor(0.8880)
tensor(0.4595) tensor(0.9020) tensor(0.8880)
tensor(0.4595) tensor(0.9020) tensor(0.8880)
tensor(0.4595) tensor(0.9020) tensor(0.8880)
tensor(0.4594) tensor(0.9020) tensor(0.8880)
tensor(0.4594) tensor(0.9020) tensor(0.8880)
tensor(0.4593) tensor(0.9020) tensor(0.8880)
tensor(0.4593) tensor(0.9020) tensor(0.8880)
tensor(0.4593) tensor(0.9020) tensor(0.8880)
tensor(0.4592) tensor(0.9020) tensor(0.8880)
tensor(0.4592) tensor(0.9020) tensor(0.8880)
tensor(0.4592) tensor(0.9030) tensor(0.8880)
tensor(0.4591) tensor(0.9030) tensor(0.8880)
tensor(0.4591) tensor(0.9030) tensor(0.8880)
tensor(0.4590) tensor(0.9030) tensor(0.8880)
tensor(0.4590) tensor(0.9030) tensor(0.8880)
tensor(0.4590) tensor(0.9030) tensor(0.8880)
tensor(0.4589) tensor(0.9030) tensor(0.8880)
tensor(0.4589) tensor(0.9030) tensor(0.8880)
tensor(0.4588) tensor(0.9030) tensor(0.8880)
tensor(0.4588) tensor(0.9030) tensor(0.8880)
tensor(0.4588) tensor(0.9030) tensor(0.8880)
tensor(0.4

tensor(0.4523) tensor(0.9080) tensor(0.8920)
tensor(0.4523) tensor(0.9080) tensor(0.8920)
tensor(0.4522) tensor(0.9080) tensor(0.8920)
tensor(0.4522) tensor(0.9080) tensor(0.8920)
tensor(0.4522) tensor(0.9080) tensor(0.8920)
tensor(0.4521) tensor(0.9080) tensor(0.8920)
tensor(0.4521) tensor(0.9080) tensor(0.8920)
tensor(0.4520) tensor(0.9080) tensor(0.8920)
tensor(0.4520) tensor(0.9080) tensor(0.8920)
tensor(0.4520) tensor(0.9080) tensor(0.8920)
tensor(0.4519) tensor(0.9080) tensor(0.8920)
tensor(0.4519) tensor(0.9080) tensor(0.8920)
tensor(0.4518) tensor(0.9080) tensor(0.8920)
tensor(0.4518) tensor(0.9080) tensor(0.8920)
tensor(0.4518) tensor(0.9080) tensor(0.8920)
tensor(0.4517) tensor(0.9080) tensor(0.8920)
tensor(0.4517) tensor(0.9080) tensor(0.8920)
tensor(0.4517) tensor(0.9080) tensor(0.8920)
tensor(0.4516) tensor(0.9080) tensor(0.8920)
tensor(0.4516) tensor(0.9080) tensor(0.8920)
tensor(0.4515) tensor(0.9080) tensor(0.8920)
tensor(0.4515) tensor(0.9080) tensor(0.8920)
tensor(0.4

tensor(0.4451) tensor(0.9130) tensor(0.8960)
tensor(0.4451) tensor(0.9130) tensor(0.8960)
tensor(0.4450) tensor(0.9130) tensor(0.8960)
tensor(0.4450) tensor(0.9120) tensor(0.8960)
tensor(0.4450) tensor(0.9130) tensor(0.8960)
tensor(0.4449) tensor(0.9130) tensor(0.8960)
tensor(0.4449) tensor(0.9130) tensor(0.8960)
tensor(0.4448) tensor(0.9130) tensor(0.8960)
tensor(0.4448) tensor(0.9130) tensor(0.8960)
tensor(0.4448) tensor(0.9130) tensor(0.8960)
tensor(0.4447) tensor(0.9130) tensor(0.8960)
tensor(0.4447) tensor(0.9130) tensor(0.8960)
tensor(0.4447) tensor(0.9130) tensor(0.8960)
tensor(0.4446) tensor(0.9130) tensor(0.8960)
tensor(0.4446) tensor(0.9130) tensor(0.8960)
tensor(0.4445) tensor(0.9130) tensor(0.8960)
tensor(0.4445) tensor(0.9130) tensor(0.8960)
tensor(0.4445) tensor(0.9130) tensor(0.8960)
tensor(0.4444) tensor(0.9130) tensor(0.8960)
tensor(0.4444) tensor(0.9130) tensor(0.8960)
tensor(0.4444) tensor(0.9130) tensor(0.8960)
tensor(0.4443) tensor(0.9130) tensor(0.8960)
tensor(0.4

In [6]:
test = model.forward(test_input)
test[test > 0] = 1
test[test <= 0] = -1

In [7]:
for i in range(1000):
    print(test[i], test_target[i])

tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.]

tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
t

tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor(