In [1]:
import torch
torch.set_grad_enabled(False)

from math import pi
from Activation import ReLU, Tanh
from Layer import Linear
from Sequential import Sequential
from Loss import LossMSE

In [2]:
def test_accuracy(model, test_input, test_target):
    
    output = model.forward(test_input)
    
    output[output >= 0] = 1
    output[output < 0] = -1
    goodValue = torch.full((len(output), 1), 0, dtype=torch.float32)
    goodValue[output == test_target] = 1
    return goodValue.sum()/len(goodValue)

In [3]:
loss = LossMSE()
model = Sequential(
            Linear(2, 25),
            ReLU(),
            Linear(25, 50),
            ReLU(),
            Linear(50, 25),
            ReLU(),
            Linear(25, 1),
            Tanh()
        )

In [4]:
train_input = torch.rand((1000,2))
train_target = torch.rand((1000,1))
train_target[((train_input-0.5)**2).sum(1) < 1/(2*pi)] = -1 
train_target[((train_input-0.5)**2).sum(1) >= 1/(2*pi)] = 1

test_input = torch.rand((1000,2))
test_target = torch.rand((1000,1))
test_target[((test_input-0.5)**2).sum(1) < 1/(2*pi)] = -1 
test_target[((test_input-0.5)**2).sum(1) >= 1/(2*pi)] = 1

#Normalization
mu, std = train_input.mean(0), train_input.std(0)
train_input.sub_(mu).div_(std)
print(test_input)
print(mu,std)
test_input.sub_(mu).div_(std)
print(test_input)

tensor([[0.2166, 0.3815],
        [0.0843, 0.5920],
        [0.3335, 0.8036],
        ...,
        [0.3836, 0.9199],
        [0.7009, 0.0166],
        [0.2785, 0.3966]])
tensor([0.4898, 0.5091]) tensor([0.2903, 0.2853])
tensor([[-0.9409, -0.4473],
        [-1.3967,  0.2906],
        [-0.5385,  1.0325],
        ...,
        [-0.3657,  1.4400],
        [ 0.7271, -1.7265],
        [-0.7277, -0.3944]])


In [ ]:
epochs = 4000
for i in range(epochs):

    output = model.forward(train_input)

    gradwrrtxL = loss.backward(output, train_target)
    model.backward(gradwrrtxL)

    if i % 10 == 0:
        test_accuracyV = test_accuracy(model, test_input, test_target)
        print(f"E {i} Loss : {loss.forward(output, train_target):.2f} / train accuracy: {test_accuracy(model, train_input, train_target):.2f} / test accuracy: {test_accuracyV:.2f}")

E 0 Loss : 1.95 / train accuracy: 0.51 / test accuracy: 0.50
E 10 Loss : 1.95 / train accuracy: 0.51 / test accuracy: 0.50
E 20 Loss : 1.95 / train accuracy: 0.51 / test accuracy: 0.50
E 30 Loss : 1.95 / train accuracy: 0.51 / test accuracy: 0.50
E 40 Loss : 1.95 / train accuracy: 0.51 / test accuracy: 0.50
E 50 Loss : 1.95 / train accuracy: 0.51 / test accuracy: 0.50
E 60 Loss : 1.95 / train accuracy: 0.51 / test accuracy: 0.50
E 70 Loss : 1.95 / train accuracy: 0.51 / test accuracy: 0.50
E 80 Loss : 1.95 / train accuracy: 0.51 / test accuracy: 0.50
E 90 Loss : 1.95 / train accuracy: 0.51 / test accuracy: 0.50
E 100 Loss : 1.95 / train accuracy: 0.51 / test accuracy: 0.50
E 110 Loss : 1.95 / train accuracy: 0.51 / test accuracy: 0.50
E 120 Loss : 1.95 / train accuracy: 0.51 / test accuracy: 0.50
E 130 Loss : 1.95 / train accuracy: 0.51 / test accuracy: 0.50
E 140 Loss : 1.95 / train accuracy: 0.51 / test accuracy: 0.50
E 150 Loss : 1.95 / train accuracy: 0.51 / test accuracy: 0.50
E 1

E 1320 Loss : 1.95 / train accuracy: 0.51 / test accuracy: 0.50
E 1330 Loss : 1.95 / train accuracy: 0.51 / test accuracy: 0.50
E 1340 Loss : 1.95 / train accuracy: 0.51 / test accuracy: 0.50
E 1350 Loss : 1.95 / train accuracy: 0.51 / test accuracy: 0.50
E 1360 Loss : 1.95 / train accuracy: 0.51 / test accuracy: 0.50
E 1370 Loss : 1.95 / train accuracy: 0.51 / test accuracy: 0.50
E 1380 Loss : 1.95 / train accuracy: 0.51 / test accuracy: 0.50
E 1390 Loss : 1.95 / train accuracy: 0.51 / test accuracy: 0.50
E 1400 Loss : 1.95 / train accuracy: 0.51 / test accuracy: 0.50
E 1410 Loss : 1.95 / train accuracy: 0.51 / test accuracy: 0.50
E 1420 Loss : 1.95 / train accuracy: 0.51 / test accuracy: 0.50
E 1430 Loss : 1.95 / train accuracy: 0.51 / test accuracy: 0.50
E 1440 Loss : 1.95 / train accuracy: 0.51 / test accuracy: 0.50
E 1450 Loss : 1.95 / train accuracy: 0.51 / test accuracy: 0.50
E 1460 Loss : 1.95 / train accuracy: 0.51 / test accuracy: 0.50
E 1470 Loss : 1.95 / train accuracy: 0.5

In [ ]:
test = model.forward(test_input)
test[test > 0] = 1
test[test <= 0] = -1

In [ ]:
for i in range(1000):
    print(test[i], test_target[i])