In [1]:
import torch
torch.set_grad_enabled(False)

from math import pi
from Activation import ReLU, Tanh
from Layer import Linear
from Sequential import Sequential
from Loss import LossMSE

In [2]:
def test_accuracy(model, test_input, test_target):
    
    output = model.forward(test_input)
    
    output[output >= 0] = 1
    output[output < 0] = -1
    goodValue = torch.full((len(output), 1), 0, dtype=torch.float32)
    goodValue[output == test_target] = 1
    return goodValue.sum()/len(goodValue)

In [3]:
loss = LossMSE()
model = Sequential(
            Linear(2, 25),
            ReLU(),
            Linear(25, 50),
            ReLU(),
            Linear(50, 25),
            ReLU(),
            Linear(25, 1),
            Tanh()
        )

In [4]:
train_input = torch.rand((1000,2))
train_target = torch.rand((1000,1))
train_target[((train_input-0.5)**2).sum(1) < 1/(2*pi)] = -1 
train_target[((train_input-0.5)**2).sum(1) >= 1/(2*pi)] = 1

test_input = torch.rand((1000,2))
test_target = torch.rand((1000,1))
test_target[((test_input-0.5)**2).sum(1) < 1/(2*pi)] = -1 
test_target[((test_input-0.5)**2).sum(1) >= 1/(2*pi)] = 1

#Normalization
mu, std = train_input.mean(0), train_input.std(0)
train_input.sub_(mu).div_(std)
print(test_input)
print(mu,std)
test_input.sub_(mu).div_(std)
print(test_input)

tensor([[0.9477, 0.9929],
        [0.0250, 0.3855],
        [0.1595, 0.4901],
        ...,
        [0.3516, 0.8351],
        [0.6575, 0.9193],
        [0.4186, 0.4123]])
tensor([0.4996, 0.4998]) tensor([0.2945, 0.2875])
tensor([[ 1.5214,  1.7149],
        [-1.6118, -0.3974],
        [-1.1550, -0.0337],
        ...,
        [-0.5028,  1.1660],
        [ 0.5360,  1.4589],
        [-0.2751, -0.3045]])


In [5]:
epochs = 4000
for i in range(epochs):

    output = model.forward(train_input)

    gradwrrtxL = loss.backward(output, train_target)
    model.backward(gradwrrtxL)

    if i % 10 == 0:
        test_accuracyV = test_accuracy(model, test_input, test_target)
        print(f"E {i} Loss : {loss.forward(output, train_target):.2f} / train accuracy: {test_accuracy(model, train_input, train_target):.2f} / test accuracy: {test_accuracyV:.2f}")

E 0 Loss : 1.80 / train accuracy: 0.57 / test accuracy: 0.58
E 10 Loss : 1.55 / train accuracy: 0.61 / test accuracy: 0.59
E 20 Loss : 1.53 / train accuracy: 0.61 / test accuracy: 0.60
E 30 Loss : 1.53 / train accuracy: 0.61 / test accuracy: 0.60
E 40 Loss : 1.50 / train accuracy: 0.62 / test accuracy: 0.61
E 50 Loss : 1.52 / train accuracy: 0.62 / test accuracy: 0.61
E 60 Loss : 1.51 / train accuracy: 0.63 / test accuracy: 0.62
E 70 Loss : 1.49 / train accuracy: 0.63 / test accuracy: 0.62
E 80 Loss : 1.47 / train accuracy: 0.63 / test accuracy: 0.62
E 90 Loss : 1.47 / train accuracy: 0.63 / test accuracy: 0.62
E 100 Loss : 1.46 / train accuracy: 0.63 / test accuracy: 0.62
E 110 Loss : 1.45 / train accuracy: 0.64 / test accuracy: 0.63
E 120 Loss : 1.44 / train accuracy: 0.63 / test accuracy: 0.63
E 130 Loss : 1.44 / train accuracy: 0.64 / test accuracy: 0.63
E 140 Loss : 1.41 / train accuracy: 0.65 / test accuracy: 0.64
E 150 Loss : 1.34 / train accuracy: 0.66 / test accuracy: 0.64
E 1

E 1310 Loss : 0.42 / train accuracy: 0.93 / test accuracy: 0.93
E 1320 Loss : 0.20 / train accuracy: 0.90 / test accuracy: 0.89
E 1330 Loss : 0.26 / train accuracy: 0.88 / test accuracy: 0.88
E 1340 Loss : 0.24 / train accuracy: 0.93 / test accuracy: 0.92
E 1350 Loss : 0.19 / train accuracy: 0.93 / test accuracy: 0.92
E 1360 Loss : 0.45 / train accuracy: 0.94 / test accuracy: 0.93
E 1370 Loss : 0.20 / train accuracy: 0.91 / test accuracy: 0.90
E 1380 Loss : 0.24 / train accuracy: 0.93 / test accuracy: 0.92
E 1390 Loss : 0.26 / train accuracy: 0.92 / test accuracy: 0.91
E 1400 Loss : 0.16 / train accuracy: 0.93 / test accuracy: 0.93
E 1410 Loss : 0.22 / train accuracy: 0.93 / test accuracy: 0.92
E 1420 Loss : 0.36 / train accuracy: 0.91 / test accuracy: 0.90
E 1430 Loss : 0.27 / train accuracy: 0.93 / test accuracy: 0.92
E 1440 Loss : 0.28 / train accuracy: 0.87 / test accuracy: 0.86
E 1450 Loss : 0.15 / train accuracy: 0.95 / test accuracy: 0.95
E 1460 Loss : 0.20 / train accuracy: 0.9

KeyboardInterrupt: 

In [ ]:
test = model.forward(test_input)
test[test > 0] = 1
test[test <= 0] = -1

In [ ]:
for i in range(1000):
    print(test[i], test_target[i])