In [1]:
import torch
import numpy as np
from Activation import ReLU
from Layer import Linear
from Sequential import Sequential
from Loss import LossMSE

In [2]:
def test_accuracy(model, test_input, test_target):
    
    output = model.forward(test_input)
    
    output[output >= 0] = 1
    output[output < 0] = -1
    goodValue = torch.full((len(output), 1), 0)
    goodValue[output == test_target] = 1
    return goodValue.sum()/len(goodValue)

In [3]:
loss = LossMSE()
model = Sequential(
            Linear(2, 25),
            ReLU(),
            Linear(25, 25),
            ReLU(),
            Linear(25, 25),
            ReLU(),
            Linear(25, 1)
        )

In [10]:
train_input = torch.rand((1000,2))
train_target = torch.rand((1000,1))
train_target[((train_input-0.5)**2).sum(1) < 1/(2*np.pi)] = -1 
train_target[((train_input-0.5)**2).sum(1) >= 1/(2*np.pi)] = 1

test_input = torch.rand((1000,2))
test_target = torch.rand((1000,1))
test_target[((test_input-0.5)**2).sum(1) < 1/(2*np.pi)] = -1 
test_target[((test_input-0.5)**2).sum(1) >= 1/(2*np.pi)] = 1

In [15]:
epochs = 4000
for i in range(epochs):


    output = model.forward(train_input)

    gradwrrtxL = loss.backward(output, train_target)
    model.backward(gradwrrtxL)

    if i % 10 == 0:
        test_accuracyV = test_accuracy(model, test_input, test_target)
        
        print(loss.forward(output, train_target), test_accuracyV, test_accuracy(model, train_input, train_target))


tensor(0.4330) tensor(0.8860) tensor(0.8850)
tensor(0.4329) tensor(0.8860) tensor(0.8850)
tensor(0.4329) tensor(0.8860) tensor(0.8850)
tensor(0.4328) tensor(0.8860) tensor(0.8850)
tensor(0.4327) tensor(0.8860) tensor(0.8850)
tensor(0.4326) tensor(0.8860) tensor(0.8850)
tensor(0.4325) tensor(0.8860) tensor(0.8850)
tensor(0.4325) tensor(0.8860) tensor(0.8850)
tensor(0.4324) tensor(0.8860) tensor(0.8850)
tensor(0.4323) tensor(0.8860) tensor(0.8860)
tensor(0.4322) tensor(0.8860) tensor(0.8860)
tensor(0.4321) tensor(0.8860) tensor(0.8860)
tensor(0.4321) tensor(0.8870) tensor(0.8860)
tensor(0.4320) tensor(0.8870) tensor(0.8860)
tensor(0.4319) tensor(0.8870) tensor(0.8860)
tensor(0.4318) tensor(0.8870) tensor(0.8860)
tensor(0.4317) tensor(0.8870) tensor(0.8860)
tensor(0.4317) tensor(0.8870) tensor(0.8860)
tensor(0.4316) tensor(0.8870) tensor(0.8860)
tensor(0.4315) tensor(0.8870) tensor(0.8860)
tensor(0.4314) tensor(0.8870) tensor(0.8860)
tensor(0.4313) tensor(0.8870) tensor(0.8860)
tensor(0.4

tensor(0.4191) tensor(0.8960) tensor(0.8910)
tensor(0.4191) tensor(0.8960) tensor(0.8910)
tensor(0.4190) tensor(0.8960) tensor(0.8910)
tensor(0.4189) tensor(0.8960) tensor(0.8910)
tensor(0.4188) tensor(0.8970) tensor(0.8910)
tensor(0.4188) tensor(0.8970) tensor(0.8910)
tensor(0.4187) tensor(0.8970) tensor(0.8910)
tensor(0.4186) tensor(0.8970) tensor(0.8910)
tensor(0.4186) tensor(0.8970) tensor(0.8920)
tensor(0.4185) tensor(0.8970) tensor(0.8920)
tensor(0.4184) tensor(0.8970) tensor(0.8920)
tensor(0.4184) tensor(0.8970) tensor(0.8920)
tensor(0.4183) tensor(0.8970) tensor(0.8920)
tensor(0.4182) tensor(0.8970) tensor(0.8920)
tensor(0.4182) tensor(0.8970) tensor(0.8920)
tensor(0.4181) tensor(0.8970) tensor(0.8910)
tensor(0.4180) tensor(0.8970) tensor(0.8920)
tensor(0.4180) tensor(0.8970) tensor(0.8920)
tensor(0.4179) tensor(0.8970) tensor(0.8930)
tensor(0.4178) tensor(0.8970) tensor(0.8930)
tensor(0.4177) tensor(0.8970) tensor(0.8930)
tensor(0.4177) tensor(0.8970) tensor(0.8930)
tensor(0.4

tensor(0.4073) tensor(0.9060) tensor(0.9030)
tensor(0.4073) tensor(0.9070) tensor(0.9030)
tensor(0.4072) tensor(0.9070) tensor(0.9030)
tensor(0.4071) tensor(0.9070) tensor(0.9030)
tensor(0.4071) tensor(0.9070) tensor(0.9030)
tensor(0.4070) tensor(0.9070) tensor(0.9030)
tensor(0.4070) tensor(0.9070) tensor(0.9030)
tensor(0.4069) tensor(0.9070) tensor(0.9030)
tensor(0.4069) tensor(0.9070) tensor(0.9030)
tensor(0.4068) tensor(0.9070) tensor(0.9030)
tensor(0.4067) tensor(0.9070) tensor(0.9030)
tensor(0.4067) tensor(0.9070) tensor(0.9020)
tensor(0.4066) tensor(0.9070) tensor(0.9020)
tensor(0.4066) tensor(0.9070) tensor(0.9030)
tensor(0.4065) tensor(0.9070) tensor(0.9030)
tensor(0.4065) tensor(0.9070) tensor(0.9030)
tensor(0.4064) tensor(0.9070) tensor(0.9030)
tensor(0.4063) tensor(0.9080) tensor(0.9030)
tensor(0.4063) tensor(0.9080) tensor(0.9030)
tensor(0.4062) tensor(0.9080) tensor(0.9040)
tensor(0.4062) tensor(0.9080) tensor(0.9040)
tensor(0.4061) tensor(0.9080) tensor(0.9040)
tensor(0.4

In [12]:
test = model.forward(test_input)
test[test > 0] = 1
test[test <= 0] = -1

In [13]:
for i in range(1000):
    print(test[i], test_target[i])

tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.

tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
te

tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([1.])
tensor([-1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor