In [1]:
import torch
torch.set_grad_enabled(False)

from math import pi
from Activation import ReLU, Tanh
from Layer import Linear
from Sequential import Sequential
from Loss import LossMSE

In [2]:
def test_accuracy(model, test_input, test_target):
    
    output = model.forward(test_input)
    
    output[output >= 0] = 1
    output[output < 0] = -1
    goodValue = torch.full((len(output), 1), 0, dtype=torch.float32)
    goodValue[output == test_target] = 1
    return goodValue.sum()/len(goodValue)

In [3]:
loss = LossMSE()
model = Sequential(
            Linear(2, 25),
            ReLU(),
            Linear(25, 50),
            ReLU(),
            Linear(50, 25),
            ReLU(),
            Linear(25, 1)
        )

In [14]:
train_input = torch.rand((1000,2))
train_target = torch.rand((1000,1))
train_target[((train_input-0.5)**2).sum(1) < 1/(2*pi)] = -1 
train_target[((train_input-0.5)**2).sum(1) >= 1/(2*pi)] = 1

test_input = torch.rand((1000,2))
test_target = torch.rand((1000,1))
test_target[((test_input-0.5)**2).sum(1) < 1/(2*pi)] = -1 
test_target[((test_input-0.5)**2).sum(1) >= 1/(2*pi)] = 1

#Normalization
mu, std = train_input.mean(), train_input.std()
train_input.sub_(mu).div_(std)
print(test_input)
print(mu,std)
test_input.sub_(mu).div_(std)
print(test_input)

tensor([[0.9866, 0.3377],
        [0.7073, 0.3779],
        [0.8053, 0.1689],
        ...,
        [0.6321, 0.2950],
        [0.6704, 0.6109],
        [0.2682, 0.0859]])
tensor(0.5022) tensor(0.2884)
tensor([[ 1.6790, -0.5705],
        [ 0.7108, -0.4310],
        [ 1.0508, -1.1557],
        ...,
        [ 0.4501, -0.7186],
        [ 0.5830,  0.3768],
        [-0.8112, -1.4434]])


In [5]:
epochs = 40000
for i in range(epochs):

    output = model.forward(train_input)

    gradwrrtxL = loss.backward(output, train_target)
    model.backward(gradwrrtxL)

    if i % 1000 == 0:
        test_accuracyV = test_accuracy(model, test_input, test_target)
        print(f"Loss : {loss.forward(output, train_target):.2f} / train accuracy: {test_accuracy(model, train_input, train_target):.2f} / test accuracy: {test_accuracyV:.2f}")

Loss : 17187.41 / train accuracy: 0.47 / test accuracy: 0.53
Loss : 11.29 / train accuracy: 0.58 / test accuracy: 0.56
Loss : 7.64 / train accuracy: 0.61 / test accuracy: 0.59
Loss : 6.02 / train accuracy: 0.63 / test accuracy: 0.61
Loss : 5.05 / train accuracy: 0.63 / test accuracy: 0.62
Loss : 4.42 / train accuracy: 0.64 / test accuracy: 0.62
Loss : 3.99 / train accuracy: 0.64 / test accuracy: 0.63
Loss : 3.63 / train accuracy: 0.65 / test accuracy: 0.64
Loss : 3.31 / train accuracy: 0.67 / test accuracy: 0.64
Loss : 3.03 / train accuracy: 0.68 / test accuracy: 0.65
Loss : 2.78 / train accuracy: 0.69 / test accuracy: 0.66
Loss : 2.56 / train accuracy: 0.69 / test accuracy: 0.66
Loss : 2.36 / train accuracy: 0.69 / test accuracy: 0.67
Loss : 2.19 / train accuracy: 0.70 / test accuracy: 0.67
Loss : 2.04 / train accuracy: 0.71 / test accuracy: 0.68
Loss : 1.91 / train accuracy: 0.72 / test accuracy: 0.68
Loss : 1.79 / train accuracy: 0.73 / test accuracy: 0.70
Loss : 1.69 / train accura

In [6]:
test = model.forward(test_input)
test[test > 0] = 1
test[test <= 0] = -1

In [7]:
for i in range(1000):
    print(test[i], test_target[i])

tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([-1.])
tensor([-1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.]

tensor([1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
t

tensor([1.]) tensor([1.])
tensor([-1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]