In [1]:
import torch
torch.set_grad_enabled(False)

from math import pi
from Activation import ReLU, Tanh
from Layer import Linear
from Sequential import Sequential
from Loss import LossMSE

In [2]:
def test_accuracy(model, test_input, test_target):
    
    output = model.forward(test_input)
    
    output[output >= 0] = 1
    output[output < 0] = -1
    goodValue = torch.full((len(output), 1), 0, dtype=torch.float32)
    goodValue[output == test_target] = 1
    return goodValue.sum()/len(goodValue)

In [3]:
loss = LossMSE()
model = Sequential(
            Linear(2, 25),
            ReLU(),
            Linear(25, 50),
            ReLU(),
            Linear(50, 50),
            ReLU(),
            Linear(50, 25),
            ReLU(),
            Linear(25, 1),
            Tanh()
        )

In [4]:
train_input = torch.rand((1000,2))
train_target = torch.rand((1000,1))
train_target[((train_input-0.5)**2).sum(1) < 1/(2*pi)] = -1 
train_target[((train_input-0.5)**2).sum(1) >= 1/(2*pi)] = 1

test_input = torch.rand((1000,2))
test_target = torch.rand((1000,1))
test_target[((test_input-0.5)**2).sum(1) < 1/(2*pi)] = -1 
test_target[((test_input-0.5)**2).sum(1) >= 1/(2*pi)] = 1

#Normalization
mu, std = train_input.mean(0), train_input.std(0)
train_input.sub_(mu).div_(std)
print(test_input)
print(mu,std)
test_input.sub_(mu).div_(std)
print(test_input)

tensor([[0.2179, 0.1033],
        [0.7415, 0.2798],
        [0.9534, 0.7657],
        ...,
        [0.6425, 0.2065],
        [0.6313, 0.2690],
        [0.3153, 0.3798]])
tensor([0.5074, 0.5103]) tensor([0.2853, 0.2893])
tensor([[-1.0145, -1.4066],
        [ 0.8205, -0.7968],
        [ 1.5634,  0.8826],
        ...,
        [ 0.4735, -1.0501],
        [ 0.4343, -0.8340],
        [-0.6732, -0.4510]])


In [5]:
epochs = 1000
for i in range(epochs):

    output = model.forward(train_input)

    gradwrrtxL = loss.backward(output, train_target)
    model.backward(gradwrrtxL)

    if i % 10 == 0:
        test_accuracyV = test_accuracy(model, test_input, test_target)
        print(f"E {i} Loss : {loss.forward(output, train_target):.2f} / train accuracy: {test_accuracy(model, train_input, train_target):.2f} / test accuracy: {test_accuracyV:.2f}")

E 0 Loss : 1.01 / train accuracy: 0.50 / test accuracy: 0.50
E 10 Loss : 1.01 / train accuracy: 0.50 / test accuracy: 0.50
E 20 Loss : 1.00 / train accuracy: 0.50 / test accuracy: 0.50
E 30 Loss : 1.00 / train accuracy: 0.52 / test accuracy: 0.51
E 40 Loss : 1.00 / train accuracy: 0.60 / test accuracy: 0.59
E 50 Loss : 0.99 / train accuracy: 0.59 / test accuracy: 0.59
E 60 Loss : 0.99 / train accuracy: 0.57 / test accuracy: 0.57
E 70 Loss : 0.99 / train accuracy: 0.56 / test accuracy: 0.56
E 80 Loss : 0.99 / train accuracy: 0.56 / test accuracy: 0.55
E 90 Loss : 0.99 / train accuracy: 0.60 / test accuracy: 0.58
E 100 Loss : 0.99 / train accuracy: 0.62 / test accuracy: 0.62
E 110 Loss : 0.99 / train accuracy: 0.66 / test accuracy: 0.66
E 120 Loss : 0.98 / train accuracy: 0.70 / test accuracy: 0.70
E 130 Loss : 0.98 / train accuracy: 0.71 / test accuracy: 0.72
E 140 Loss : 0.98 / train accuracy: 0.71 / test accuracy: 0.72
E 150 Loss : 0.98 / train accuracy: 0.70 / test accuracy: 0.72
E 1

In [6]:
test = model.forward(test_input)
test[test > 0] = 1
test[test <= 0] = -1

In [7]:
for i in range(1000):
    print(test[i], test_target[i])

tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
te

tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tens

tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([-1.]) tensor([-1.])
tensor([1.]) tensor([1.])
tensor([1.]) tensor([1.])
tensor(